config/routes.rb
Rails.application.routes.draw do
  get 'users/sign_up_params'
  devise_for :users, controllers: { registrations: 'users' }
  resources :socios
  resources :socios do
    resources :likes, only: [:create, :destroy]
  end
  resources :socios do
    resources :comments, only: [:create, :destroy]
  end
  
  resources :relationships, only: [:create, :destroy]
  root "socios#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :socio

    validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :socio
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/socio.rb
class Socio < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader
    mount_uploader :video, VideoUploader
    has_many :likes, dependent: :destroy
    has_many :comments
    validates :title, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :socios
  has_many :likes
  has_many :comments



  # Define the relationships
  has_many :active_relationships, class_name: 'Relationship',
                                 foreign_key: 'follower_id',
                                 dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name: 'Relationship',
                                  foreign_key: 'followed_id',
                                  dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower





  def likes?(socio)
    likes.where(socio_id: socio.id).exists?
  end
  
  mount_uploader :avatar, AvatarUploader

  validates :name, :dob, :gender, presence: true


  



    # Follow a user
    def follow(other_user)
      active_relationships.create(followed: other_user)
    end
  
    # Unfollow a user
    def unfollow(other_user)
      active_relationships.find_by(followed: other_user).destroy
    end
  
    # Check if the current user is following another user
    def following?(other_user)
      following.include?(other_user)
    end

    def followers_count
      followers.count
    end
  
    def following_count
      following.count
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

def create
    @socio = Socio.find(params[:socio_id])
    @comment = @socio.comments.build(comment_params)
    @comment.user = current_user
  
    if @comment.save
        redirect_to socio_path(@socio), notice: 'Comment was successfully created.'
    else
      # Handle validation errors or other errors here
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to socio_path(@comment.socio), notice: 'Comment was successfully deleted.'
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user! # Ensure users are logged in
    before_action :find_socio
    before_action :find_like, only: [:destroy]
    # skip_before_action :verify_authenticity_token, only: [:update]
    def create
      @socio = Socio.find(params[:socio_id])
      # like = current_user.likes.build(socio: @socio)
      if already_liked?
        flash[:notice] = 'You cannot like more than once'
      else
        @socio.likes.create(user_id: current_user.id)
      end
      redirect_to socio_path(@socio)
    end
  
    def destroy
      # @like = Like.find(params[:id])
      if !(already_liked?)
        flash[:notice] = 'Cannot unlike'
      else
        @like.destroy
      end
      redirect_to socio_path(@socio)
    end
    
    private
    
    def find_socio
      @socio = Socio.find_by(id: params[:id])
    end

    def already_liked?
      Like.where(user_id: current_user.id, socio_id: params[:socio_id]).exists?
    end

    def find_like
      @socio = Socio.find(params[:socio_id])
      @like = @socio.likes.find(params[:id])
    end
    
  end
  

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    user_to_follow = User.find(params[:user_id])
    current_user.follow(user_to_follow)
    redirect_to socio_path(params[:socio_id])
  end

  def destroy
    relationship = current_user.active_relationships.find_by(id: params[:id])
    # relationship = Relationship.find(params[:id])
    user_to_unfollow = relationship.followed
    relationship.destroy
    # current_user.unfollow(user_to_unfollow)
    redirect_to socio_path(params[:socio_id]), notice: 'You have unfollowed this user.'
  end
end

app/controllers/socios_controller.rb
class SociosController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    # before_action :set_socio, only: [:edit, :update, :destroy]
    


    def index
        @socios = Socio.all
        # render :index
    end

    def show
        @socio = Socio.find(params[:id])
        @user = @socio.user
        @like = current_user&.likes&.find_by(socio: @socio)
        # The @blog_post instance variable is already set by set_blog_post method
    end
    
    def new
        @socio = Socio.new
    end
    
    def create
        @socio = current_user.socios.new(socio_params)
        if @socio.save
          redirect_to @socio, notice: 'Socio was successfully created.'
        else
          render :new
        end
    end
    
    def edit
        @socio = Socio.find(params[:id])
        if current_user == @socio.author
            # render :edit
            # Allow the author to edit the post
        else
            redirect_to socios_path, alert: 'You are not authorized to edit this post.'
        end
    end
    
    def update
        @socio = Socio.find(params[:id])
        if @socio.update(socio_params)
          redirect_to @socio, notice: 'Socio was successfully updated.'
        else
          render :edit
        end
    end
    
    def destroy
        @socio = Socio.find(params[:id])
        if current_user == @socio.user
            @socio.destroy
            redirect_to socios_url, notice: 'Socio was successfully destroyed.'
        else
            redirect_to socios_url, alert: 'You are not authorized to delete this post.'
        end
    end
    
    private
    
    def set_socio
        @socio = current_user.socios.find(params[:id])
    end
    
    def socio_params
        params.require(:socio).permit(:title, :description, :image, :video)
    end

    def like
        @socios = Socio.includes(:likes).all
        @socio = Socio.find(params[:id])
        current_user.likes.create(socio: @socio)
        redirect_to socios_path, notice: 'You liked this socio.'
    end
    
    def unlike
        @socio = Socio.find(params[:id])
        current_user.likes.find_by(socio: @socio).destroy
        redirect_to socios_path, notice: 'You unliked this socio.'
    end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  def follow
    @user = User.find(params[:id])
    current_user.follow(@user)
    redirect_to @user
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.unfollow(@user)
    redirect_to @user
  end

  private 
  
  def sign_up_params
    params.require(:user).permit(:name, :dob, :gender, :email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/socios_helper.rb
module SociosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Social3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <%= csrf_meta_tags %>
  </head>

  <body>

    <header>
      <div class="left-section">
        <%= link_to "Home", root_path %>
      </div>
      <div class="right-section">
        <% if user_signed_in? %>
          <% if current_user.avatar? %>
            <%= image_tag current_user.avatar.url , width: "3%", class: "round-image" %>
          <% end %>
          <%= current_user.name %>
          <%= button_to 'Log out', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure you want to log out?' } %>
        <% else %>
          <%= link_to "Login", new_user_session_path %>
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </header>
    
    <%= yield %>
  </body>
</html>

app/views/socios/_form.html.erb
<%= form_with(model: @socio, local: true) do |form| %>
  <!-- ... Existing fields ... -->
  
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  
  <div class="field">
    <%= form.label :video %>
    <%= form.file_field :video %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/socios/comment_form.html.erb
<%# <h2>Add a Comment</h2>
<%= form_for([@socio, @socio.comments.build]) do |f| %>
  <%# <div class="field">
    <%= f.text_area :content, placeholder: 'Write your comment here' %>
  <%# </div>
  <div class="actions">
    <%= f.submit 'Submit Comment' %>
  <%# </div>
<%# <% end %>

app/views/socios/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>
<%= form_for @socio do |f| %>
  <!--%= f.submit "Update" %-->
<% end %>
<%= link_to 'Show', @socio %> |
<%= link_to 'Back', socios_path %>

<!--%= link_to "Like", like_socio_path(socio), method: :post, class: 'btn btn-primary' %-->

app/views/socios/index.html.erb
<div class="index-container">

<h1>Socios</h1>
<%= link_to 'Create New Socio', new_socio_path %>

<% @socios.each do |socio| %>
  <h2 class="socio"><%= link_to socio.title, socio %></h2>
  <h2 class="socio"><%= link_to socio.description, socio %></h2>

  <% if socio.image? %>
      <%= image_tag socio.image.url , width: "20%"%>
  <% end %>

  <% if socio.video? %>
      <video width="320" height="240" controls>
        <source src="<%= socio.video.url %>" type="video/mp4">
      </video>
  <% end %>

  <% if socio.user.avatar? %>
      <div class="user-info">
        <p>Posted by <%= image_tag socio.user.avatar.url , width: "3%", class: "round-image" %> <%= socio.user.email %> on <%= socio.created_at.strftime("%B %d, %Y") %></p>
      </div>
  <% else %>
      <p>Posted by <%= socio.user.email %> on <%= socio.created_at.strftime("%B %d, %Y") %></p>
      
  <% end %>

  <p class="meta">
    <p>Name: <%= socio.user.name %></p>
    <p>Dob: <%= socio.user.dob %></p>
    <p>Gender: <%= socio.user.gender %></p>
  </p>




  <h1>-----------------------------------------------------------------------------------------------</h1>

  <br>
  <br>
<% end %>

</div>

app/views/socios/new.html.erb
<div class="new-socio-container">
  <h1>New Socio</h1>
  <%= render 'form' %>
  <%= link_to 'Back', socios_path %>
</div>

app/views/socios/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @socio.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @socio.description %>
</p>

<% if @socio.image.present? %>
  <p>
    <strong>Image:</strong>
    <%= image_tag @socio.image.url %>
  </p>
<% end %>

<% if @socio.video.present? %>
  <p>
    <strong>Video:</strong>
    <video width="500" controls>
      <source src="<%= @socio.video.url %>" type="video/mp4">
    </video>
  </p> 
<% end %>

<!-- Display likes count -->
<p><%= @socio.likes.count %> <%= (@socio.likes.count) == 1 ? 'Like' : 'Likes'%></p>
<!-- Display followers count -->
<p>Followers: <%= @user.followers_count %></p>
<!-- Display following count -->
<p>Following: <%= @user.following_count %></p>


<% pre_like = @socio.likes.find { |like| like&.user_id == current_user&.id} %>
<% if pre_like %>
  <%= button_to 'Unlike', socio_like_path(@socio, pre_like.id), method: :delete %>
<% else %>
  <%= button_to 'Like', socio_likes_path(@socio), method: :post%>
<% end %>

<h2>Comments</h2>
<% @socio.comments.each do |comment| %>
  <div class="comment">
    <p><strong><%= comment.user.email %>:</strong></p>
    <p><%= comment.content %></p>
  </div>
<% end %>
<%= form_with(model: [@socio, Comment.new]) do |form| %>
    <%= form.text_area :content, placeholder: "Add a comment..." %>
    <%= form.submit "Comment" %>
<% end %>





<% user_to_follow = @socio.user %>


<% unless current_user.id == user_to_follow.id %>
  <% unless current_user&.following?(user_to_follow) %>
    <%= button_to 'Follow', relationships_path(user_id: user_to_follow.id, socio_id: @socio), method: :post %>
  <% else %>
    <%= button_to 'Unfollow', relationship_path(current_user.active_relationships.find_by(followed_id: user_to_follow.id), socio_id: @socio), method: :delete %>
  <% end %>
<% end %>



<% if @socio.user == current_user %>
  <%= button_to 'Delete', socio_path(@socio), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' } %>
<% end %> 
<% if current_user == @socio.user %>
  <%= link_to 'Edit |', edit_socio_path(@socio) %>
<% end %> 
<%= link_to 'Back', socios_path %>

app/views/users/sign_up_params.html.erb
<h1>Users#sign_up_params</h1>
<p>Find me in app/views/users/sign_up_params.html.erb</p>